Repository fairer-iOS/fairer-iOS, pull requests merged in 2022-09, with the labels that each got.

#9 [ADD] MainButton 생성
  fairer-iOS/fairer-iOS.xcodeproj/project.xcworkspace/xcuserdata/gim-yuna.xcuserdatad/UserInterfaceState.xcuserstate
  fairer-iOS/fairer-iOS.xcodeproj/xcuserdata/gim-yuna.xcuserdatad/xcschemes/xcschememanagement.plist
  fairer-iOS/fairer-iOS/Global/Extension/UIButton+Extension.swift
  fairer-iOS/fairer-iOS/Global/Extension/UIColor+Extension.swift
  fairer-iOS/fairer-iOS/Global/UIComponent/MainButton.swift
Labels: Add

#11 [ADD] 홈 화면 네비게이션, 툴바 추가
  fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
  fairer-iOS/fairer-iOS/Global/Base/BaseViewController.swift
  fairer-iOS/fairer-iOS/Global/Literal/ImageLiteral.swift
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/fairerlogo.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/fairerlogo.imageset/fairerlogo.pdf
  fairer-iOS/fairer-iOS/Global/Supports/SceneDelegate.swift
  fairer-iOS/fairer-iOS/Screens/Home/HomeViewController.swift
  fairer-iOS/fairer-iOS/Screens/Home/UIComponent/HomeViewControllerToolBar.swift
Labels: Add

#13 [ADD] HomeView TitleLabel, CollectionView 추가
  fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
  fairer-iOS/fairer-iOS/Global/Base/BaseUIView.swift
  fairer-iOS/fairer-iOS/Global/Extension/UILabel+Extension.swift
  fairer-iOS/fairer-iOS/Screens/Home/HomeViewController.swift
  fairer-iOS/fairer-iOS/Screens/Home/UIComponent/HomeGroupCollectionView.swift
  fairer-iOS/fairer-iOS/Screens/Home/UIComponent/HomeGroupCollectionViewCell.swift
Labels: UI🎨

#15 [ADD] OnboardingNameView UI & Logic
  fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
  fairer-iOS/fairer-iOS/Global/Extension/String+Extension.swift
  fairer-iOS/fairer-iOS/Global/Extension/UIFont+Extension.swift
  fairer-iOS/fairer-iOS/Global/Extension/UITextField+Extension.swift
  fairer-iOS/fairer-iOS/Global/Literal/ImageLiteral.swift
  fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/clearbutton.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/clearbutton.imageset/btn_clear.pdf
  fairer-iOS/fairer-iOS/Screens/OnboardingName/OnboardingNameViewController.swift
Labels: UI🎨, Add

#23 [ADD] LaunchScreen(SplashView) 추가
  fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
  fairer-iOS/fairer-iOS/Global/Literal/ImageLiteral.swift
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/fairerlogosplash.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/fairerlogosplash.imageset/Group 326.pdf
  fairer-iOS/fairer-iOS/Global/Supports/Info.plist
Labels: Add

#18 [ADD] OnboardingProfileView UI & Logic
  fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
  fairer-iOS/fairer-iOS/Global/Literal/ImageLiteral.swift
  fairer-iOS/fairer-iOS/Global/Literal/SizeLiteral.swift
  fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/button/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/button/backbutton.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/button/backbutton.imageset/arrow_back_ios.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/button/clearbutton.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/button/clearbutton.imageset/btn_clear.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profileblue3.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profileblue3.imageset/profileblue3.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profileblue4.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profileblue4.imageset/profileblue4.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profilegreen1.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profilegreen1.imageset/profilegreen1.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profilegreen3.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profilegreen3.imageset/profilegreen3.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profileindigo3.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profileindigo3.imageset/profileindigo3.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profilelightblue1.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profilelightblue1.imageset/profilelightblue1.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profilelightblue2.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profilelightblue2.imageset/profilelightblue2.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profilenone.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profilenone.imageset/profilenone.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profileorange1.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profileorange1.imageset/profileorange1.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profileorange2.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profileorange2.imageset/profileorange2.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profilepink1.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profilepink1.imageset/profilepink1.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profilepink3.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profilepink3.imageset/profilepink3.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profilepurple1.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profilepurple1.imageset/profilepurple1.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profilepurple2.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profilepurple2.imageset/profilepurple2.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profilepurple3.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profilepurple3.imageset/profilepurple3.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profileyellow1.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profileyellow1.imageset/profileyellow1.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profileyellow2.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/profile/profileyellow2.imageset/profileyellow2.pdf
  fairer-iOS/fairer-iOS/Screens/OnboardingName/OnboardingNameViewController.swift
  fairer-iOS/fairer-iOS/Screens/OnboardingProfile/OnboardingProfileViewController.swift
  fairer-iOS/fairer-iOS/Screens/OnboardingProfile/UIComponent/OnboardingProfileGroupCollectionView.swift
  fairer-iOS/fairer-iOS/Screens/OnboardingProfile/UIComponent/OnboardingProfileGroupCollectionViewCell.swift
Labels: Add

#20 [ADD] HomeGroup 추가
  fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
  fairer-iOS/fairer-iOS.xcodeproj/xcshareddata/xcschemes/fairer-iOS.xcscheme
  fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
  fairer-iOS/fairer-iOS/Screens/Home/HomeViewController.swift
  fairer-iOS/fairer-iOS/Screens/Home/UIComponent/HomeGroupCollectionViewCell.swift
  fairer-iOS/fairer-iOS/Screens/Home/UIComponent/HomeRuleView.swift
Labels: UI🎨, HomeView, Add

#25 [ADD] LoginView UI 구현
  fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
  fairer-iOS/fairer-iOS/Global/Extension/UILabel+Extension.swift
  fairer-iOS/fairer-iOS/Global/Literal/ImageLiteral.swift
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/logo/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/logo/applelogo.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/logo/applelogo.imageset/applelogo.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/logo/fairerlogo.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/logo/fairerlogo.imageset/fairerlogo.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/logo/fairerlogologin.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/logo/fairerlogologin.imageset/Logo.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/logo/fairerlogosplash.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/logo/fairerlogosplash.imageset/Group 326.pdf
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/logo/googlelogo.imageset/Contents.json
  fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/logo/googlelogo.imageset/googlelogo.pdf
  fairer-iOS/fairer-iOS/Screens/Login/LoginViewController.swift
Labels: Add

#27 [ADD] DatePicker 추가
  fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
  fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
  fairer-iOS/fairer-iOS/Screens/Home/HomeViewController.swift
  fairer-iOS/fairer-iOS/Screens/Home/UIComponent/HomeCalendarView.swift
  fairer-iOS/fairer-iOS/Screens/Home/UIComponent/HomeViewControllerToolBar.swift
Labels: UI🎨, HomeView, Add
